name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:
  dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to Dev Databricks Workspace
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          chmod +x deploy.sh
          ./deploy.sh dev

   


